version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bossing-postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bossing-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    command: ["java", "-jar", "app.jar"]

volumes:
  postgres_data:
